# Generated by Django 5.2 on 2025-05-15 06:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('result', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('jackpot', 'Jackpot')], max_length=10)),
                ('win_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('numbers', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('bet', 'Bet'), ('win', 'Win'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='GameResult',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='game.player'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='game_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='game.gamesession'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='game.player'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['player', 'created_at'], name='game_gamese_player__d60815_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['created_at'], name='game_gamese_created_f4d519_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['player', 'created_at'], name='game_transa_player__c0012f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='game_transa_transac_d4c450_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='game_transa_created_52d7f4_idx'),
        ),
    ]
