# Generated by Django 5.2 on 2025-05-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamesession_player_transaction_delete_gameresult_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-created_at'], 'verbose_name': 'Гравець', 'verbose_name_plural': 'Гравці'},
        ),
        migrations.AddField(
            model_name='player',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='result',
            field=models.CharField(choices=[('WIN', 'Перемога'), ('LOSS', 'Поразка'), ('JACKPOT', 'Джекпот')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('BET', 'Ставка'), ('WIN', 'Виграш'), ('DEPOSIT', 'Поповнення'), ('WITHDRAWAL', 'Зняття'), ('BONUS', 'Бонус')], max_length=20),
        ),
    ]
